### ISSUE TITLE
Redirect bitcore-node-dash to dashevo repository

### ISSUE THREAD

**Issue by Alex-Werner** [dashpay/dashcore-node#22]
Hey @UdjinM6 @nmarley 

Could we redirect to https://github.com/dashevo/bitcore-node-dash this repository :) 

(Same goes for other repository such as bitcore-lib-dash, insight-api-dash etc...)

**Comment by UdjinM6** [comment]
I believe @schinzelh is the best to ask for repo transfer/redirect/whatever :)

**Comment by nmarley** [comment]
For the Github links to work this way, we'll probably have to co-ordinate this in a specific order, e.g.:

1. Rename dashpay/bitcore-node-dash to dashpay/bitcore-node-dash.old (in order to retain history/issues/PRs, etc.)
2. Transfer dashevo/bitcore-node-dash to dashpay
3. Transfer dashpay/bitcore-node-dash _back_ to dashevo

... but I'll defer to @schinzelh as well on this.

**Comment by nmarley** [comment]
Talked w/@schinzelh and he's ok w/this strategy, but unfortunately https://github.com/dashevo/bitcore-node-dash isn't a fork of this one (which is a bitpay fork), so if we try that then we'll lose the bitpay upstream link, which is something I believe we want to keep.

I'd recommend we do this instead:

1. first merge outstanding PR's in the dashevo repo
2. then PR from dashevo into here & merge

...at this point both versions will be in-sync.

3. remove the dashevo one
4. make a true fork into dashevo
5. finish the above strategy, which will make dashpay re-direct to dashevo as well as maintain the bitpay upstream link

**Comment by nmarley** [comment]
Once we get all the issues/PR's resolved in this repo and codebases are synced, I will create the appropriate re-direct to dashevo.

**Comment by akfranco** [comment]
This issue was moved to dashevo/dashcore-node#36

**Comment by nmarley** [comment]
To be done once issues / PRs closed
